# Stage 1: Build the application
FROM node:18 AS builder
RUN apt-get update && apt-get install -y make g++ python3
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
COPY prisma ./prisma/
COPY system ./system/
RUN npm install
RUN npx prisma generate

# Copy the rest of the source code
COPY . .

# Stage 2: Run the application
FROM node:18
WORKDIR /usr/src/app

# Copy necessary files from the builder stage
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/system ./system

# Install netcat (openbsd version) with apt
RUN apt-get update && apt-get install -y netcat-openbsd

# Clean up to reduce image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose port
EXPOSE 3000

# Set the default command
CMD ["npm", "run", "dev"]
